In [233]:
import numpy as np

In [234]:
import pandas as pd

In [236]:
df=pd.read_csv(r"C:\Users\Daniel\Downloads\Python pract\BIA\Linear\Housing.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [237]:
print(" R\u00b2 = %.3f")

 R² = %.3f

In [238]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [239]:
df.shape

(545, 13)

In [240]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [241]:
# This already gives you the encoded DataFrame - no need for OneHotEncoder
sep_col = pd.get_dummies(df[['mainroad','guestroom', 'basement', 'hotwaterheating', 
                           'airconditioning', 'prefarea', 'furnishingstatus']], drop_first=True)

print("Encoded columns:")
print(sep_col.columns.tolist())
print("\nFirst few rows:")
print(sep_col.head())

# sep_col is already your encoded DataFrame - use it directly
lt_cl = sep_col.copy()

Encoded columns:
['mainroad_yes', 'guestroom_yes', 'basement_yes', 'hotwaterheating_yes', 'airconditioning_yes', 'prefarea_yes', 'furnishingstatus_semi-furnished', 'furnishingstatus_unfurnished']

First few rows:
   mainroad_yes  guestroom_yes  basement_yes  hotwaterheating_yes  \
0          True          False         False                False
1          True          False         False                False
2          True          False          True                False
3          True          False          True                False
4          True           True          True                False

   airconditioning_yes  prefarea_yes  furnishingstatus_semi-furnished  \
0                 True          True                            False
1                 True         False                            False
2                False          True                             True
3                 True          True                            False
4                 True         False                            False

   furnishingstatus_unfurnished
0                         False
1                         False
2                         False
3                         False
4                         False

In [242]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore')
encoded_data = ohe.fit_transform(df[['mainroad', 'guestroom', 'basement', 'hotwaterheating',
                                   'airconditioning', 'prefarea', 'furnishingstatus']])

# Simply convert to integer
lt_cl = pd.DataFrame(encoded_data.astype(int), columns=ohe.get_feature_names_out())

print(lt_cl.head())
print("\nUnique values:", lt_cl.values.flatten())

   mainroad_yes  guestroom_yes  basement_yes  hotwaterheating_yes  \
0             1              0             0                    0
1             1              0             0                    0
2             1              0             1                    0
3             1              0             1                    0
4             1              1             1                    0

   airconditioning_yes  prefarea_yes  furnishingstatus_semi-furnished  \
0                    1             1                                0
1                    1             0                                0
2                    0             1                                1
3                    1             1                                0
4                    1             0                                0

   furnishingstatus_unfurnished
0                             0
1                             0
2                             0
3                             0
4                             0

Unique values: [1 0 0 ... 0 0 1]

In [247]:
lt_cl

,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,1,0,0,0,1,1,0,0
1,1,0,0,0,1,0,0,0
2,1,0,1,0,0,1,1,0
3,1,0,1,0,1,1,0,0
4,1,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...
540,1,0,1,0,0,0,0,1
541,0,0,0,0,0,0,1,0
542,1,0,0,0,0,0,0,1
543,0,0,0,0,0,0,0,0
544,1,0,0,0,0,0,0,1

In [249]:
df_n=pd.concat([df,lt_cl],axis='columns')

In [250]:
df_n

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,...,prefarea,furnishingstatus,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,yes,no,no,no,yes,...,yes,furnished,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,yes,no,no,no,yes,...,no,furnished,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,yes,no,yes,no,no,...,yes,semi-furnished,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,yes,no,yes,no,yes,...,yes,furnished,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,...,no,furnished,1,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,...,no,unfurnished,1,0,1,0,0,0,0,1
541,1767150,2400,3,1,1,no,no,no,no,no,...,no,semi-furnished,0,0,0,0,0,0,1,0
542,1750000,3620,2,1,1,yes,no,no,no,no,...,no,unfurnished,1,0,0,0,0,0,0,1
543,1750000,2910,3,1,1,no,no,no,no,no,...,no,furnished,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,yes,no,no,no,no,...,no,unfurnished,1,0,0,0,0,0,0,1

In [251]:
df_n=df_n.drop(['mainroad', 'guestroom', 'basement', 'hotwaterheating','airconditioning', 'prefarea', 'furnishingstatus'],axis='columns')
df_n

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,2,1,0,1,0,0,0,0,1
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1,0
542,1750000,3620,2,1,1,0,1,0,0,0,0,0,0,1
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,0,1,0,0,0,0,0,0,1

In [252]:
inp_var=df_n.drop(['price'],axis='columns')
target=df_n.price

In [254]:
inp_var

,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,7420,4,1,2,2,1,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,2,1,0,1,0,0,0,0,1
541,2400,3,1,1,0,0,0,0,0,0,0,1,0
542,3620,2,1,1,0,1,0,0,0,0,0,0,1
543,2910,3,1,1,0,0,0,0,0,0,0,0,0
544,3850,3,1,2,0,1,0,0,0,0,0,0,1

In [258]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inp_var,target,test_size=0.3,random_state=70)

In [259]:
from sklearn.linear_model import LinearRegression
linear_model=LinearRegression()

In [263]:
linear_model.fit(x_train,y_train)

LinearRegression()

In [264]:
y_predict=linear_model.predict(x_test)

In [266]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predict)

0.6848688682533888

In [159]:
final.corr()

,price,area,bedrooms,bathrooms,stories,parking,furnishingstatus_semi-furnished,furnishingstatus_unfurnished,prefarea_yes,airconditioning_yes,hotwaterheating_yes,basement_yes,guestroom_yes,mainroad_yes
price,1.000000,0.535997,0.366494,0.517545,0.420712,0.384394,0.063656,-0.280587,0.329777,0.452954,0.093073,0.187057,0.255517,0.296898
area,0.535997,1.000000,0.151858,0.193820,0.083996,0.352980,0.006156,-0.142278,0.234779,0.222393,-0.009229,0.047417,0.140297,0.288874
bedrooms,0.366494,0.151858,1.000000,0.373930,0.408564,0.139270,0.050040,-0.126252,0.079023,0.160603,0.046049,0.097312,0.080549,-0.012033
bathrooms,0.517545,0.193820,0.373930,1.000000,0.326165,0.177496,0.029834,-0.132107,0.063472,0.186915,0.067159,0.102106,0.126469,0.042398
stories,0.420712,0.083996,0.408564,0.326165,1.000000,0.045547,-0.003648,-0.082972,0.044425,0.293602,0.018847,-0.172394,0.043538,0.121706
parking,0.384394,0.352980,0.139270,0.177496,0.045547,1.000000,0.041327,-0.165705,0.091627,0.159173,0.067864,0.051497,0.037466,0.204433
furnishingstatus_semi-furnished,0.063656,0.006156,0.050040,0.029834,-0.003648,0.041327,1.000000,-0.588405,-0.011535,-0.053179,0.063819,0.050284,0.005821,0.011450
furnishingstatus_unfurnished,-0.280587,-0.142278,-0.126252,-0.132107,-0.082972,-0.165705,-0.588405,1.000000,-0.081271,-0.094086,-0.059194,-0.117935,-0.099023,-0.133123
prefarea_yes,0.329777,0.234779,0.079023,0.063472,0.044425,0.091627,-0.011535,-0.081271,1.000000,0.117382,-0.059411,0.228083,0.160897,0.199876
airconditioning_yes,0.452954,0.222393,0.160603,0.186915,0.293602,0.159173,-0.053179,-0.094086,0.117382,1.000000,-0.130023,0.047341,0.138179,0.105423
hotwaterheating_yes,0.093073,-0.009229,0.046049,0.067159,0.018847,0.067864,0.063819,-0.059194,-0.059411,-0.130023,1.000000,0.004385,-0.010308,-0.011781
basement_yes,0.187057,0.047417,0.097312,0.102106,-0.172394,0.051497,0.050284,-0.117935,0.228083,0.047341,0.004385,1.000000,0.372066,0.044002
guestroom_yes,0.255517,0.140297,0.080549,0.126469,0.043538,0.037466,0.005821,-0.099023,0.160897,0.138179,-0.010308,0.372066,1.000000,0.092337
mainroad_yes,0.296898,0.288874,-0.012033,0.042398,0.121706,0.204433,0.011450,-0.133123,0.199876,0.105423,-0.011781,0.044002,0.092337,1.000000